name: Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Configurer Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installer les dépendances système (GUI)
      # Nécessaire car ttkbootstrap/tkinter a besoin de bibliothèques graphiques
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Installer les dépendances Python
      # python -m pip freeze | findstr "ttkbootstrap cryptography pyinstaller" > requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install flake8
        pip install -r requirements.txt

    - name: Analyse de la qualité du code (Flake8)
      run: |
        # 1. Arrête le build s'il y a des erreurs de syntaxe ou des variables indéfinies
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # 2. Affiche les avertissements de style (PEP8) sans bloquer le build (--exit-zero)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Lancer les tests
      # xvfb-run n'est pas nécessaire pour les tests logiques (et non reconnu sous Windows)
      run: |
        coverage run --omit=crypto_gui.py -m unittest test_crypto.py
        coverage xml

    - name: Upload coverage reports to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
